export const countryTranslations = [
  { country: 'Afghanistan', label: 'アフガニスタン' },
  { country: 'Åland Islands', label: 'オーランド諸島' },
  { country: 'Albania', label: 'アルバニア' },
  { country: 'Algeria', label: 'アルジェリア' },
  { country: 'American Samoa', label: 'アメリカ領サモア' },
  { country: 'Andorra', label: 'アンドラ' },
  { country: 'Angola', label: 'アンゴラ' },
  { country: 'Anguilla', label: 'アンギラ' },
  { country: 'Antarctica', label: '南極大陸' },
  { country: 'Antigua and Barbuda', label: 'アンティグア・バーブーダ' },
  { country: 'Argentina', label: 'アルゼンチン' },
  { country: 'Armenia', label: 'アルメニア' },
  { country: 'Aruba', label: 'アルバ' },
  { country: 'Australia', label: 'オーストラリア' },
  { country: 'Austria', label: 'オーストリア' },
  { country: 'Azerbaijan', label: 'アゼルバイジャン' },
  { country: 'Bahamas', label: 'バハマ' },
  { country: 'Bahrain', label: 'バーレーン' },
  { country: 'Bangladesh', label: 'バングラデシュ' },
  { country: 'Barbados', label: 'バルバドス' },
  { country: 'Belarus', label: 'ベラルーシ' },
  { country: 'Belgium', label: 'ベルギー' },
  { country: 'Belize', label: 'ベリーズ' },
  { country: 'Benin', label: 'ベナン' },
  { country: 'Bermuda', label: 'バミューダ' },
  { country: 'Bhutan', label: 'ブータン' },
  { country: 'Bolivia, Plurinational State of', label: 'ボリビア多民族国' },
  {
    country: 'Bonaire, Sint Eustatius and Saba',
    label: 'ボネール、シント・ユースタティウスおよびサバ',
  },
  { country: 'Bosnia and Herzegovina', label: 'ボスニア・ヘルツェゴビナ' },
  { country: 'Botswana', label: 'ボツワナ' },
  { country: 'Bouvet Island', label: 'ブーベ島' },
  { country: 'Brazil', label: 'ブラジル' },
  {
    country: 'British Indian Ocean Territory',
    label: 'イギリス領インド洋地域',
  },
  { country: 'Brunei Darussalam', label: 'ブルネイ・ダルサラーム' },
  { country: 'Bulgaria', label: 'ブルガリア' },
  { country: 'Burkina Faso', label: 'ブルキナファソ' },
  { country: 'Burundi', label: 'ブルンジ' },
  { country: 'Cambodia', label: 'カンボジア' },
  { country: 'Cameroon', label: 'カメルーン' },
  { country: 'Canada', label: 'カナダ' },
  { country: 'Cape Verde', label: 'カーボベルデ' },
  { country: 'Cayman Islands', label: 'ケイマン諸島' },
  { country: 'Central African Republic', label: '中央アフリカ共和国' },
  { country: 'Chad', label: 'チャド' },
  { country: 'Chile', label: 'チリ' },
  { country: 'China', label: '中国' },
  { country: 'Christmas Island', label: 'クリスマス島' },
  { country: 'Cocos (Keeling) Islands', label: 'ココス（キーリング）諸島' },
  { country: 'Colombia', label: 'コロンビア' },
  { country: 'Comoros', label: 'コモロ' },
  { country: 'Congo, Republic of the (Brazzaville)', label: 'コンゴ共和国 (ブラザヴィル)' },
  { country: 'Congo, the Democratic Republic of the (Kinshasa)', label: 'コンゴ民主共和国（キンシャサ）' },
  { country: 'Cook Islands', label: 'クック諸島' },
  { country: 'Costa Rica', label: 'コスタリカ' },
  { country: "Côte d'Ivoire, Republic of",label: "コートジボワール共和国" },
  { country: 'Croatia', label: 'クロアチア' },
  { country: 'Cuba', label: 'キューバ' },
  { country: 'Curaçao', label: 'キュラソー' },
  { country: 'Cyprus', label: 'キプロス' },
  { country: 'Czech Republic',label:"チェコ共和国" },
  { country: 'Denmark', label: 'デンマーク' },
  { country: 'Djibouti', label: 'ジブチ' },
  { country: 'Dominica', label: 'ドミニカ' },
  { country: 'Dominican Republic', label: 'ドミニカ共和国' },
  { country: 'Ecuador', label: 'エクアドル' },
  { country: 'Egypt', label: 'エジプト' },
  { country: 'El Salvador', label: 'エルサルバドル' },
  { country: 'Equatorial Guinea', label: '赤道ギニア' },
  { country: 'Eritrea', label: 'エリトリア' },
  { country: 'Estonia', label: 'エストニア' },
  { country: 'Ethiopia', label: 'エチオピア' },
  { country: 'Falkland Islands (Islas Malvinas)',label:"フォークランド諸島 (マルビナス諸島)" },
  { country: 'Faroe Islands', label: 'フェロー諸島' },
  { country: 'Fiji', label: 'フィジー' },
  { country: 'Finland', label: 'フィンランド' },
  { country: 'France', label: 'フランス' },
  { country: 'French Guiana', label: 'フランス領ギアナ' },
  { country: 'French Polynesia', label: 'フランス領ポリネシア' },
  { country: 'French Southern and Antarctic Lands',label:"フランス南部および南極大陸" },
  { country: 'Gabon', label: 'ガボン' },
  { country: 'Gambia, The',label: "ガンビア" },
  { country: 'Georgia', label: 'ジョージア' },
  { country: 'Germany', label: 'ドイツ' },
  { country: 'Ghana', label: 'ガーナ' },
  { country: 'Gibraltar', label: 'ジブラルタル' },
  { country: 'Greece', label: 'ギリシャ' },
  { country: 'Greenland', label: 'グリーンランド' },
  { country: 'Grenada', label: 'グレナダ' },
  { country: 'Guadeloupe', label: 'グアドループ' },
  { country: 'Guam', label: 'グアム' },
  { country: 'Guatemala', label: 'グアテマラ' },
  { country: 'Guernsey', label: 'ガーンジー' },
  { country: 'Guinea', label: 'ギニア' },
  { country: 'Guinea-Bissau', label: 'ギニアビサウ' },
  { country: 'Guyana', label: 'ガイアナ' },
  { country: 'Haiti', label: 'ハイチ' },
  {
    country: 'Heard Island and McDonald Islands',
    label: 'ハード島とマクドナルド諸島',
  },
  { country: 'Holy See (Vatican City)' , label: 'ローマ教皇庁 (バチカン市国)'},
  { country: 'Honduras', label: 'ホンジュラス' },
  { country: 'Hong Kong', label: '香港' },
  { country: 'Hungary', label: 'ハンガリー' },
  { country: 'Iceland', label: 'アイスランド' },
  { country: 'India', label: 'インド' },
  { country: 'Indonesia', label: 'インドネシア' },
  { country: 'Iran, Islamic Republic of', label: 'イラン・イスラム共和国' },
  { country: 'Iraq', label: 'イラク' },
  { country: 'Ireland', label: 'アイルランド' },
  { country: 'Isle of Man', label: 'マン島' },
  { country: 'Israel', label: 'イスラエル' },
  { country: 'Italy', label: 'イタリア' },
  { country: 'Jamaica', label: 'ジャマイカ' },
  { country: 'Japan', label: '日本' },
  { country: 'Jersey', label: 'ジャージー' },
  { country: 'Jordan', label: 'ヨルダン' },
  { country: 'Kazakhstan', label: 'カザフスタン' },
  { country: 'Kenya', label: 'ケニア' },
  { country: 'Kiribati', label: 'キリバス' },
  {
    country: "Korea, Democratic People's Republic of",
    label: '朝鮮民主主義人民共和国',
  },
  { country: 'Korea, Republic of', label: '大韓民国' },
  { country: 'Kosovo' ,label:"コソボ" },
  { country: 'Kuwait', label: 'クウェート' },
  { country: 'Kyrgyzstan', label: 'キルギス' },
  { country: 'Laos', label:"ラオス" },
  { country: 'Latvia', label: 'ラトビア' },
  { country: 'Lebanon', label: 'レバノン' },
  { country: 'Lesotho', label: 'レソト' },
  { country: 'Liberia', label: 'リベリア' },
  { country: 'Libya', label: 'リビア' },
  { country: 'Liechtenstein', label: 'リヒテンシュタイン' },
  { country: 'Lithuania', label: 'リトアニア' },
  { country: 'Luxembourg', label: 'ルクセンブルク' },
  { country: 'Macao', label: 'マカオ' },
  { country: 'Macedonia, Republic of',label:"マケドニア共和国" },
  { country: 'Madagascar', label: 'マダガスカル' },
  { country: 'Malawi', label: 'マラウイ' },
  { country: 'Malaysia', label: 'マレーシア' },
  { country: 'Maldives', label: 'モルディブ' },
  { country: 'Mali', label: 'マリ' },
  { country: 'Malta', label: 'マルタ' },
  { country: 'Marshall Islands', label: 'マーシャル諸島' },
  { country: 'Martinique', label: 'マルティニーク' },
  { country: 'Mauritania', label: 'モーリタニア' },
  { country: 'Mauritius', label: 'モーリシャス' },
  { country: 'Mayotte', label: 'マヨット' },
  { country: 'Mexico', label: 'メキシコ' },
  { country: 'Micronesia, Federated States of', label: 'ミクロネシア連邦' },
  { country: 'Moldova', label:"モルドバ"},
  { country: 'Monaco', label: 'モナコ' },
  { country: 'Mongolia', label: 'モンゴル' },
  { country: 'Montenegro', label: 'モンテネグロ' },
  { country: 'Montserrat', label: 'モントセラト' },
  { country: 'Morocco', label: 'モロッコ' },
  { country: 'Mozambique', label: 'モザンビーク' },
  { country: 'Myanmar', label: 'ミャンマー' },
  { country: 'Namibia', label: 'ナミビア' },
  { country: 'Nauru', label: 'ナウル' },
  { country: 'Nepal', label: 'ネパール' },
  { country: 'Netherlands', label: 'オランダ' },
  { country: 'New Caledonia', label: 'ニューカレドニア' },
  { country: 'New Zealand', label: 'ニュージーランド' },
  { country: 'Nicaragua', label: 'ニカラグア' },
  { country: 'Niger', label: 'ニジェール' },
  { country: 'Nigeria', label: 'ナイジェリア' },
  { country: 'Niue', label: 'ニウエ' },
  { country: 'Norfolk Island', label: 'ノーフォーク島' },
  { country: 'Northern Mariana Islands', label: '北マリアナ諸島' },
  { country: 'Norway', label: 'ノルウェー' },
  { country: 'Oman', label: 'オマーン' },
  { country: 'Pakistan', label: 'パキスタン' },
  { country: 'Palau', label: 'パラオ' },
  { country: 'Palestine, State of', label: 'パレスチナ' },
  { country: 'Panama', label: 'パナマ' },
  { country: 'Papua New Guinea', label: 'パプアニューギニア' },
  { country: 'Paraguay', label: 'パラグアイ' },
  { country: 'Peru', label: 'ペルー' },
  { country: 'Philippines', label: 'フィリピン' },
  { country: 'Pitcairn', label: 'ピトケアン諸島' },
  { country: 'Poland', label: 'ポーランド' },
  { country: 'Portugal', label: 'ポルトガル' },
  { country: 'Puerto Rico', label: 'プエルトリコ' },
  { country: 'Qatar', label: 'カタール' },
  { country: 'Réunion', label: 'レユニオン' },
  { country: 'Romania', label: 'ルーマニア' },
  { country: 'Russian Federation', label: 'ロシア連邦' },
  { country: 'Rwanda', label: 'ルワンダ' },
  { country: 'Saint Barthélemy', label: 'サン・バルテルミー' },
  {
    country: 'Saint Helena, Ascension and Tristan da Cunha',
    label: 'セントヘレナ・アセンションおよびトリスタンダクーニャ',
  },
  { country: 'Saint Kitts and Nevis', label: 'セントクリストファー・ネイビス' },
  { country: 'Saint Lucia', label: 'セントルシア' },
  {
    country: 'Saint Martin (French part)',
    label: 'サン・マルタン（フランス領）',
  },
  { country: 'Saint Pierre and Miquelon', label: 'サンピエール島・ミクロン島' },
  {
    country: 'Saint Vincent and the Grenadines',
    label: 'セントビンセントおよびグレナディーン諸島',
  },
  { country: 'Samoa', label: 'サモア' },
  { country: 'San Marino', label: 'サンマリノ' },
  { country: 'Sao Tome and Principe', label: 'サントメ・プリンシペ' },
  { country: 'Saudi Arabia', label: 'サウジアラビア' },
  { country: 'Senegal', label: 'セネガル' },
  { country: 'Serbia', label: 'セルビア' },
  { country: 'Seychelles', label: 'セーシェル' },
  { country: 'Sierra Leone', label: 'シエラレオネ' },
  { country: 'Singapore', label: 'シンガポール' },
  {
    country: 'Sint Maarten (Dutch part)',
    label: 'シント・マールテン（オランダ領）',
  },
  { country: 'Slovakia', label: 'スロバキア' },
  { country: 'Slovenia', label: 'スロベニア' },
  { country: 'Solomon Islands', label: 'ソロモン諸島' },
  { country: 'Somalia', label: 'ソマリア' },
  { country: 'South Africa', label: '南アフリカ' },
  { country: 'South Georgia and South Sandwich Islands',label:"サウスジョージア島とサウスサンドイッチ諸島" },
  { country: 'South Sudan', label: '南スーダン' },
  { country: 'Spain', label: 'スペイン' },
  { country: 'Sri Lanka', label: 'スリランカ' },
  { country: 'Sudan', label: 'スーダン' },
  { country: 'Suriname', label: 'スリナム' },
  { country: 'Eswatini', label: 'エスワティニ' },
  { country: 'Sweden', label: 'スウェーデン' },
  { country: 'Switzerland', label: 'スイス' },
  { country: 'Syrian Arab Republic', label: 'シリア・アラブ共和国' },
  { country: 'Taiwan' , label:"台湾"},
  { country: 'Tajikistan', label: 'タジキスタン' },
  { country: 'Tanzania, United Republic of', label: 'タンザニア連合共和国' },
  { country: 'Thailand', label: 'タイ' },
  { country: 'Timor-Leste', label: '東ティモール' },
  { country: 'Togo', label: 'トーゴ' },
  { country: 'Tokelau', label: 'トケラウ' },
  { country: 'Tonga', label: 'トンガ' },
  { country: 'Trinidad and Tobago', label: 'トリニダード・トバゴ' },
  { country: 'Tunisia', label: 'チュニジア' },
  { country: 'Turkey', label: 'トルコ' },
  { country: 'Turkmenistan', label: 'トルクメニスタン' },
  { country: 'Turks and Caicos Islands', label: 'タークス・カイコス諸島' },
  { country: 'Tuvalu', label: 'ツバル' },
  { country: 'Uganda', label: 'ウガンダ' },
  { country: 'Ukraine', label: 'ウクライナ' },
  { country: 'United Arab Emirates', label: 'アラブ首長国連邦' },
  { country: 'United Kingdom', label: 'イギリス' },
  { country: 'United States', label: 'アメリカ合衆国' },
  {
    country: 'United States Minor Outlying Islands',
    label: '合衆国領有小離島',
  },
  { country: 'Uruguay', label: 'ウルグアイ' },
  { country: 'Uzbekistan', label: 'ウズベキスタン' },
  { country: 'Vanuatu', label: 'バヌアツ' },
  {
    country: 'Venezuela, Bolivarian Republic of',
    label: 'ベネズエラ・ボリバル共和国',
  },
  { country: 'Vietnam',label: "ベトナム"},
  { country: 'Virgin Islands, British', label: 'イギリス領ヴァージン諸島' },
  { country: 'Virgin Islands, U.S.', label: 'アメリカ領ヴァージン諸島' },
  { country: 'Wallis and Futuna', label: 'ウォリス・フツナ' },
  { country: 'Western Sahara', label: '西サハラ' },
  { country: 'Yemen', label: 'イエメン' },
  { country: 'Zambia', label: 'ザンビア' },
  { country: 'Zimbabwe', label: 'ジンバブエ' },
];
